# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
branches:
    only:
        - master
apt_packages:
 - gdtools

matrix:
 include:
 - r: release
   os: linux
 - r: release
   os: osx
 - r: devel
   os: linux
 - r: oldrel
   os: linux
 - r: oldrel
   os: osx

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"

warnings_are_errors: false

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings
