# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      r: oldrel
    - os: linux
      dist: precise
      r: release
    - os: linux
      dist: precise
      r: devel
    - os: linux
      dist: trusty
      r: oldrel
    - os: linux
      dist: trusty
      r: release
    - os: linux
      dist: trusty
      r: devel
    - os: osx
      dist: precise
      r: oldrel
    - os: osx
      dist: precise
      r: release
    - os: osx
      dist: precise
      r: devel
    - os: osx
      dist: trusty
      r: oldrel
    - os: osx
      dist: trusty
      r: release
    - os: osx
      dist: trusty
      r: devel


env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"

warnings_are_errors: false


r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings
