# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
branches:
    only:
        - master
latex: false

matrix:
 include:
 - r: release
   os: linux
 - r: devel
   os: linux

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"

warnings_are_errors: false


before_deploy:
  - sudo apt-get install -y libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev
  - Rscript -e 'remotes::install_cran("devtools"); remotes::install_cran("pkgdown"); remotes::install_version("rmarkdown", "1.15")'
  - wget https://raw.githubusercontent.com/selcenari/ceRNAnetsim/services/_pkgdown.yaml
  - wget https://raw.githubusercontent.com/selcenari/ceRNAnetsim/services/codecov.yml
  - wget https://raw.githubusercontent.com/selcenari/ceRNAnetsim/services/deploy.sh

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master

